import type { Metadata } from 'next';
import './globals.css';
import StyledComponentsRegistry from './styling/styled-components/registry';
import { Providers } from './redux/provider';
import { inter } from './fonts';

export const metadata: Metadata = {
  title: 'MyResume',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={inter.className}>
        <Providers>
          <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
        </Providers>
      </body>
    </html>
  );
}
